CREATE TABLE subs (
    name TEXT PRIMARY KEY,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE posts
ADD CONSTRAINT fk_posts_subs
FOREIGN KEY (sub) REFERENCES subs(name)
ON DELETE CASCADE
ON UPDATE CASCADE;
